### ISSUE TITLE
A clear outline of user requirements and the process used to determine user requirements.

### ISSUE THREAD

**Issue by alilinares** [kalapyha/solitaire-group-9#20]

**Comment by ilona-kutuzova** [comment]
Products features should be translated into Epics and User Stories.

**Comment by ilona-kutuzova** [comment]
Documented the outline of user requirements in the form of Epics, User Stories (include Story Points estimations and Acceptance Criteria) and Sprints.

[CST8334_Assignment1_PartI_Question2.docx](https://github.com/kalapyha/solitaire-group-9/files/10614072/CST8334_Assignment1_PartI_Question2.docx)

**Comment by kalapyha** [comment]
@ilona-kutuzova Great job, a lot of user stories
